#!/usr/bin/env python
# dependencies python-xmpp mpg123 fortune

from config import *
from do_stuff import *
from jabberbot import JabberBot, botcmd
import datetime
import subprocess
import re
import logging
logging.basicConfig(filename="pibot.log",
                    filemode='a',
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.DEBUG)

class MUCJabberBot(JabberBot):


    def __init__(self, *args, **kwargs):
        ''' Initialize variables. '''

        # answer only direct messages or not?
        self.only_direct = kwargs.get('only_direct', False)
        try:
            del kwargs['only_direct']
        except KeyError:
            pass

        # initialize jabberbot
        super(MUCJabberBot, self).__init__(*args, **kwargs)

        # create a regex to check if a message is a direct message
        user, domain = str(self.jid).split('@')
        self.direct_message_re = re.compile('^%s(@%s)?[^\w]? ' \
                % (user, domain))

    def callback_message(self, conn, mess):
        ''' Changes the behaviour of the JabberBot in order to allow
        it to answer direct messages. This is used often when it is
        connected in MUCs (multiple users chatroom). '''

        message = mess.getBody()
        if not message:
            return

        if self.direct_message_re.match(message):
            mess.setBody(' '.join(message.split(' ', 1)[1:]))
            return super(MUCJabberBot, self).callback_message(conn, mess)
        elif not self.only_direct:
            return super(MUCJabberBot, self).callback_message(conn, mess)


class PiBot(MUCJabberBot):

    @botcmd
    def fail(self, mess, args):
        play_from_dir("fail")

    @botcmd
    def win(self, mess, args):
        play_from_dir("win")
    
    @botcmd
    def fortune(self, mess, args):
        text = subprocess.check_output(["fortune","-s"])
        self.send_simple_reply(mess, text.replace('\n',' '))

    @botcmd
    def moep(self, mess, args):
        self.send_simple_reply(mess, "MOEP!")
        play_from_dir("moep")

    @botcmd
    def muhaha(self, mess, args):
        self.send_simple_reply(mess, "MUHAHA!")
        play_misc("muhaha.wav")

    @botcmd
    def sani(self, mess, args):
        play_misc("def.mp3")
        
    @botcmd
    def project(self, mess, args):
        if ("SUCCESS" in args) or ("FIXED" in args):
            play_from_dir("win")
        elif "FAIL" in args:
            play_from_dir("fail")

    @botcmd
    def slap(self, mess, args):
        play_misc("slap.wav")

    @botcmd
    def sg(self, mess, args):
        play_misc("super-geil.mp3")

    @botcmd
    def yippie(self, mess, args):
         play_misc("yippi.mp3")



if __name__ == '__main__':

    mucbot = PiBot(username, password, only_direct=False)
    mucbot.muc_join_room(chatroom, nickname)
    mucbot.serve_forever()
